repos:
  - repo: local
    hooks:
      - id: flutter-format
        name: Flutter Format
        entry: flutter format
        language: system
        files: \.dart$
        args: [--set-exit-if-changed]
        
      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        files: \.dart$
        args: [--fatal-infos]
        
      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        files: \.dart$
        args: [--coverage]