name: flutter_ebook_app
description: A Flutter app for eBooks

publish_to: 'none'

version: 1.0.4+8

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.2
  freezed_annotation: ^2.4.4
  google_fonts: ^4.0.4
  iridium_reader_widget:
    path: packages/reader_widget
  logman: ^0.0.14
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^2.3.5
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  share_plus: ^7.2.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  xml2json: ^6.2.7

## dependency_overrides: (none)

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^2.5.2
  riverpod_generator: ^2.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/books/
